### ISSUE TITLE
Epic: Move/port identified `yapapi` bits to `golem-core`

### ISSUE THREAD

**Issue by approxit** [golemfactory/golem-core-python#57]
After #54 and #55, we can finally cut out `yapapi` dependencies to get `golem-core` into state, with no python-golem-related stuff at the lower layer, just directly `yagna`.

**Note**: check both yapapi's version for each bit (^0.9.3 and newest)
**Note**: Ensure that examples are working

```[tasklist]
### Bits
- [ ] https://github.com/golemfactory/golem-core-python/issues/77
- [ ] https://github.com/golemfactory/golem-core-python/issues/76
- [ ] https://github.com/golemfactory/golem-core-python/issues/75
- [ ] https://github.com/golemfactory/golem-core-python/issues/74
- [ ] https://github.com/golemfactory/golem-core-python/issues/73
- [ ] https://github.com/golemfactory/golem-core-python/issues/93
- [ ] https://github.com/golemfactory/golem-core-python/issues/92
- [ ] https://github.com/golemfactory/golem-core-python/issues/91
- [ ] Rewrite README
```

**Comment by lucekdudek** [comment]
### Tasks
- [ ] Bump yapapi to newest version before porting features
- [ ] Copy blender image source code (used in examples) from yapapi to golem-core-python
- [ ] Port/reimplemnt Payload along with `yapapi.payload.vm` and other `yapapi.payload` artifacts in golem-core:
    - [ ] refactor golem-core's `Package.from_image_hash` so it doesn't spin asyncio event loop
    - [ ] refactor yappai's `Package.resolve_url()` so it returns plain url instead of str decorated with prefix and sufix
